spring.application.name=academias-backend

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/academias_db
spring.datasource.username=academias_user
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Cloudinary
cloudinary.cloud-name=dadjbbua7
cloudinary.api-key=868515754275929
cloudinary.api-secret=YJ7-zItUa2TFadfBIoX88g2aTow
cloudinary.folder=academias/alumnos

# Para subir archivos
server.tomcat.max-part-count=200
server.tomcat.max-parameter-count=20000
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

spring.jpa.properties.hibernate.type.preferred_enum_jdbc_type=NAMED_ENUM


# Server
server.port=8080
