# Railway PostgreSQL
spring.datasource.url=${DATABASE_URL}
spring.datasource.driver-class-name=org.postgresql.Driver

# Menos logs
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# Railway PORT
server.port=${PORT}

# Cloudinary
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

# Auth0
spring.security.oauth2.resourceserver.jwt.issuer-uri=${AUTH0_ISSUER_URI}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${AUTH0_JWK_SET_URI}
auth0.audience=${AUTH0_AUDIENCE}