# PostgreSQL local
spring.datasource.url=jdbc:postgresql://localhost:5432/academias_db
spring.datasource.username=academias_user
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# Logs SQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Puerto local
server.port=8080

# Cloudinary
cloudinary.cloud-name=dadjbbua7
cloudinary.api-key=868515754275929
cloudinary.api-secret=zItUa2TFadfBIoX88g2aTow

# Auth0
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://nairbdev-auth.us.auth0.com/
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://nairbdev-auth.us.auth0.com/.well-known/jwks.json
auth0.audience=https://academias-api