spring.application.name=academias-backend

# Perfil activo por defecto
spring.profiles.active=dev

# JPA común
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.type.preferred_enum_jdbc_type=NAMED_ENUM

# Uploads
server.tomcat.max-part-count=200
server.tomcat.max-parameter-count=20000
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# Cloudinary
cloudinary.folder=academias/alumnos



