spring.application.name=academias-backend
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.type.preferred_enum_jdbc_type=NAMED_ENUM

server.tomcat.max-part-count=200
server.tomcat.max-parameter-count=20000
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

cloudinary.folder=academias/alumnos